name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Construir com Maven
      run: mvn -B package --file pom.xml

    - name: Submeter dependências ao Dependency Graph
      uses: advanced-security/maven-dependency-submission-action@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ignore-maven-wrapper: true
