name: Version Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar instalação do Maven
        run: |
            echo "=== Versão do Maven ==="
            mvn -version