name: Version Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug versão Maven sem filtragem
        run: |
          echo "=== Testando extração da versão do Maven ==="
          mvn help:evaluate -Dexpression=project.version -q -DforceStdout || echo "Erro ao executar o Maven!"